service: employeesProject

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
    
  
functions:
  create:
    handler: src/modules/employees/UseCase/createEmployee/createEmployeeController.handle
    events:
      - http:
          path: /create
          method: POST
          cors: true
  listEmployee:
    handler: src/modules/employees/UseCase/listEmployee/listEmployeeController.handle
    events:
      - http:
          path: /listEmployee
          method: GET
          cors:
  updateEmployee:
    handler: src/modules/employees/useCases/updateEmployee/updateEmployeeController.handle
    events:
      - http:
          path: /updateEmployee/{id}
          method: PATCH
          cors: true
  viewEmployee:
    handler: src/modules/employees/useCases/viewEmployee/viewEmployeeController.handle
    events:
      - http:
          path: /viewEmployee/{id}
          method: GET
          cors: true
resources:
  Resources:
    dbEmployees:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          writeCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH